plugins {
    id 'java'
}

group = 'Lab10'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

dependencies {
    implementation project (':Model')

    // Hibernate Core
    implementation 'org.hibernate.orm:hibernate-core:6.4.4.Final'

    // SQLite driver
    implementation 'org.xerial:sqlite-jdbc:3.45.1.0'

    // Dialect pentru SQLite
    implementation 'org.hibernate.orm:hibernate-community-dialects:6.4.4.Final'

    implementation group: 'org.apache.logging.log4j', name: 'log4j-core', version: '2.22.1'
    implementation group: 'org.apache.logging.log4j', name: 'log4j-api', version: '2.22.1'

    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}