plugins {
    id 'java'
    id 'application'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

application {
    mainClass = 'client.TestClientJava'
}


repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework:spring-web:6.1.3'
    implementation 'org.springframework:spring-context:6.1.3'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.16.1'
    implementation 'org.apache.httpcomponents.client5:httpclient5:5.3.1'

    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}